default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "db/development.sqlite3"

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db8im0l63nedn8
  username: diceqdgdkszqls
  host: ec2-44-209-158-64.compute-1.amazonaws.com
  password: 822a7b6c0f8fd738b85bf03c59ca13644008150a6ac1520d1ad61234b85fafc7

