default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "db/development.sqlite3"

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: dbm8of7982sq72
  username: hksnceezrnkivf
  host: ec2-44-209-158-64.compute-1.amazonaws.com
  password: ac9850bbf969c8d046e55867c8a93d00fceb177e87fc2fd32e9d2704aaea606f
